### ISSUE TITLE
Docker :  Sandbox runtime failed: Sandbox did not start in time: /tmp/sandbox_qqk18dku/sandbox/started still does not exist

### ISSUE THREAD

**Issue by SuperPat45** [EtiennePerot/open-webui-code-execution#39]
## Description

I started Open WebUI from a docker container, and the tool execution throw the error:

> Sandbox runtime failed: Sandbox did not start in time: /tmp/sandbox_qqk18dku/sandbox/started still does not exist

## General information

- **Open WebUI version**: v0.6.5
- **Tool/function version**: v0.8.0
- **Open WebUI setup**:
  - **Kernel information**: Linux xxxxx 6.11.0-21-generic 21-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 19 16:50:40 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
  - **Runtime**: Docker
  - If running in Docker:
    - **Docker version**: 28.0.4, build b8034c0
    - **`docker run` command**: sudo docker compose up -d
    - **Docker container info**:
[docker_info.txt](https://github.com/user-attachments/files/19794707/docker_info.txt)

## Debug logs

[chat-export-1744894726661.json](https://github.com/user-attachments/files/19794552/chat-export-1744894726661.json)

## Additional context

My docker compose file:
```
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - 'WEBUI_SECRET_KEY='
      - 'ENV=dev'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    volumes:
      - /opt/openwebui/data:/app/backend/data
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: false
    security_opt:
      - seccomp=unconfined
```
