### ISSUE TITLE
Docker: Sandbox runtime failed: OSError: write_uid_map (#1): [Errno 1] Operation not permitted (other attempts: write_uid_map

### ISSUE THREAD

**Issue by SuperPat45** [EtiennePerot/open-webui-code-execution#40]
## Description

I started Open WebUI from a docker container, and the tool execution throw the error:

> Sandbox runtime failed: OSError: write_uid_map (#1): [Errno 1] Operation not permitted (other attempts: write_uid_map...

## General information

- **Open WebUI version**: v0.6.5
- **Tool/function version**: v0.8.0
- **Open WebUI setup**:
  - **Kernel information**: Linux xxxxx 6.11.0-21-generic 21-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 19 16:50:40 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
  - **Runtime**: Docker
  - If running in Docker:
    - **Docker version**: 28.0.4, build b8034c0
    - **`docker run` command**: sudo docker compose up -d
    - **Docker container info**:
[dockerinspect.txt](https://github.com/user-attachments/files/19794889/dockerinspect.txt)

## Debug logs

[chat-export-1744895663586.json](https://github.com/user-attachments/files/19794904/chat-export-1744895663586.json)

## Additional context

My docker compose file:
```
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - 'WEBUI_SECRET_KEY='
      - 'ENV=dev'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    volumes:
      - /opt/openwebui/data:/app/backend/data
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    security_opt:
      - seccomp:unconfined
      - apparmor=unconfined
      - label=type:container_engine_t
```
